# Basic Site Settings
locale                   : "en-US"
minimal_mistakes_skin    : "air"
title                    : "Shahnewaz Sakib | Assistant Professor, UTC 🧑‍🔬"
title_separator          : "-"
name                     : &name "Shahnewaz's Website"
description              : &description "Personal Website"
url                      : "https://shahanewaz.github.io"
baseurl                  : ""
repository               : "Shahnewaz/shahnewaz_website.github.io"

# Site Author (Sidebar Profile)
author:
  avatar           : "/images/profile.jpg"
  name             : "Shahnewaz Sakib"
  bio              : "Researcher in AI safety and privacy-preserving machine learning, focused on turning theory into practice"
  location         : "Chattanooga, TN"
  employer         : "University of Tennessee at Chattanooga"
  email            : "shahnewazkarim-sakib@utc.edu"
  googlescholar    : "https://scholar.google.com/citations?user=u5JRM_EAAAAJ&hl=en"
  linkedin         : "shahnewaz-karim-sakib"
  # github: "Shahanewaz"   ← removed to stop “Follow: GitHub” in footer

# Footer cleanup
footer:
  links: []  # remove Follow and GitHub
copyright:
  enabled: false  # remove attribution

# Collection Settings
include:
  - .htaccess
  - _pages
  - files
exclude:
  - node_modules
  - vendor
  - README
  - LICENSE
  - Gemfile*
  - .sass-cache
  - .jekyll-cache
  - .bundle
  - tmp
  - _site

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true

# Output and Build
permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
timezone: Etc/UTC
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-redirect-from

whitelist:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-redirect-from

compress_html:
  clippings: all
  ignore:
    envs: development
