###############################################################################
#  Basic site settings
###############################################################################
locale                  : "en-US"
minimal_mistakes_skin   : "air"

title                   : "Shahnewaz Sakib 🧑‍🔬"
title_separator         : "-"
name                    : "Shahnewaz's Website"
description             : "Personal website"

# ––– GitHub Pages plumbing –––
url       : "https://shahanewaz.github.io"      # always without trailing /
baseurl   : ""      # leading slash **ONLY** if you keep the repo name
# (If you rename the repo to shahanewaz.github.io, change the line above to: baseurl: "")

repository: "Shahanewaz/shahnewaz_website.github.io"

###############################################################################
#  Sidebar / author box
###############################################################################
author:
  avatar      : "profile_pic_2.png"            # path is correct – picture exists :contentReference[oaicite:0]{index=0}
  name        : "Shahnewaz Sakib"
  bio         : "Researcher in AI safety & privacy‑preserving ML – turning theory into practice"
  location    : "Chattanooga, TN"
  employer    : "UT Chattanooga"
  email       : "shahnewazkarim-sakib@utc.edu"
  googlescholar: "https://scholar.google.com/citations?user=DgtMVfQAAAAJ&hl=en"
  linkedin    : "shahnewaz-karim-sakib"
  # github    : "Shahanewaz"      # ⟵ comment‑out or delete → footer bullet disappears

###############################################################################
#  Footer
###############################################################################
footer:
  links: []              # explicit empty list suppresses the “Follow:” section
  copyright:
    enabled: false       # hide the Minimal‑Mistakes attribution

atom_feed:
  hide: true          # removes the “Follow: Feed” entry

###############################################################################
#  Content collections
###############################################################################
collections:
  teaching   : {output: true, permalink: /:collection/:path/}
  publications: {output: true, permalink: /:collection/:path/}
  portfolio  : {output: true, permalink: /:collection/:path/}
  talks      : {output: true, permalink: /:collection/:path/}

###############################################################################
#  Build & plugin settings
###############################################################################
permalink : /:categories/:title/
markdown  : kramdown
highlighter: rouge
timezone  : America/New_York          # pick yours

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-redirect-from

###############################################################################
#  Include / exclude
###############################################################################
include:
  - .htaccess
  - _pages
  - files
exclude:
  - node_modules
  - vendor
  - README
  - LICENSE
  - Gemfile*
  - .sass-cache
  - .jekyll-cache
  - .bundle
  - tmp
  - _site

###############################################################################
#  YAML defaults for various content types
###############################################################################
defaults:
  - scope: {path: "", type: posts}
    values: {layout: single, author_profile: true, read_time: true, comments: false, share: true}

  - scope: {path: "", type: pages}
    values: {layout: single, author_profile: true}

  - scope: {path: "", type: teaching}
    values: {layout: single, author_profile: true}

  - scope: {path: "", type: publications}
    values: {layout: single, author_profile: true}

  - scope: {path: "", type: portfolio}
    values: {layout: single, author_profile: true}

  - scope: {path: "", type: talks}
    values: {layout: talk, author_profile: true}

###############################################################################
#  Optional: compress the final HTML
###############################################################################
compress_html:
  clippings : all
  ignore    : []
  envs      : ["production"]
